---
- name: centos7lab1
  distrib: "centos/7"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.10
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.10
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "centos7"

- name: centos7lab2
  distrib: "centos/7"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.11
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.11
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "centos7"

- name: centos8lab1
  distrib: "centos/8"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.12
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.12
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "centos8"

- name: centos8lab2
  distrib: "centos/8"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.13
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.13
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "centos8"

- name: ubuntu20lab1
  distrib: "ubuntu/20.04"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.14
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.14
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "ubuntu2004"

- name: ubuntu20lab2
  distrib: "ubuntu/20.04"
  vmversion: "1.0.0"
  network:
    ens161:
      ip: 192.168.56.15
      netmask: 255.255.255.0
    ens192:
      ip: 192.168.57.15
      netmask: 255.255.255.0
  memory: 1024
  cpus: 1
  os: "ubuntu2004"
